### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by TF1130** [TF1130/furima_28324#9]
#URL
https://furima-28324.herokuapp.com/
#認証ID,PASS
admin
2222
#購入者
test999@test.co.jp
test999
#出品者
test100@test.co.jp
test10
#購入用カード
card number 4242424242424242
exp_month/exp_year 03月/23年
cvc 123

**Comment by mo1015** [comment]
深澤さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○**ログイン後、出品するボタンを押しても出品ページへ遷移しない**

※商品出品機能や購入機能は次回以降確認させていただきます

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○商品を出品するとsold outの表示になってしまう**


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mo1015** [comment]
失礼いたしました。
修正できましたら、**以下の最終課題完了報告フォームを再度提出お願いします！**
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mutorisa** [comment]
深澤さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、前回ご指摘させていただいた項目の修正は確認できました✨
ただし、追加で以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○出品商品の詳細及び商品説明が表示されていないので、表示させましょう。**

**○出品商品の購入ができないので、購入できるようにしましょう。**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mutorisa** [comment]
深澤さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、商品詳細及び商品説明が表示されていることは確認できました✨
しかし、商品を購入する際、Issueに記載していただいている、カード情報を入力しても商品の購入ができませんでした。
暗証番号を「123」と入力しても「Token can't be blank」とエラーが出てしまいます。今一度正常に購入ができるか、ご確認をお願いします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、商品の購入はできました✨
ただし、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○一度購入した商品が再度購入できてしまう為、一度購入した商品は購入できないようにしましょう。**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
